### ISSUE TITLE
Fix Firefox rendering of stylesheet

### ISSUE THREAD

**Issue by gdonald** [bkuhlmann/hanamismith#2]
After following the 'typical workflow' commands, my &lt;li&gt;s are rendering differently compared to the image on https://alchemists.io/projects/hanamismith:

<img width="1918" alt="Screenshot 2023-08-13 at 7 38 44 PM" src="https://github.com/bkuhlmann/hanamismith/assets/42317655/12c4075a-3054-4e0b-8a76-7fb0448fc4a5">

<p>&nbsp;</p>

Also, the image file 'apple.png' is being loaded remotely instead of being access from the public directory with the other static assets:

<img width="524" alt="Screenshot 2023-08-13 at 7 51 20 PM" src="https://github.com/bkuhlmann/hanamismith/assets/42317655/6ebcb833-a819-4690-8b44-12982f4c19c1">

**Comment by bkuhlmann** [comment]
Hey Greg. :wave: 

Thanks for catching this. It's because I'm using [CSS Nesting](https://caniuse.com/?search=CSS%20Nesting). To fix, ensure you have this setting enabled:

![2023-08-14_07-12-47-Firefox](https://github.com/bkuhlmann/hanamismith/assets/50245/72b85d91-3ccf-49d8-ba98-f288c85db074)

Currently, Firefox 116.0.2 is the most recent version but this will be fully supported in 117.0.0. I'm planning to leverage CSS Nesting heavily moving forward so don't plan to make any further updates since Version 117.0.0 is almost here.

---

Regarding the assets, those are being loaded remotely on purpose with the idea you'd customize as desired. This is being done to avoid checking binary data into your Git repository since that is a bad practice and not supported via link:https://alchemists.io/projects/git-lint[Git Lint].

One alternative would be to encode the assets as Data URIs. If you feel strongly about that, I could explore doing that which would still be safe for Git purposes since Git could easily diff the changes since it wouldn't binary data.

I'm going to close this issue for now but feel free to continue the conversation if you like.
