### ISSUE TITLE
Add Hanami beta support

### ISSUE THREAD

**Issue by gdonald** [bkuhlmann/hanamismith#3]
Can we get support for the Hanami beta?

`gem install hanami --pre`

Thanks.

**Comment by bkuhlmann** [comment]
Hey Greg. So use of pre versions breaks _strict semantic versioning_ . It's something I wish wasn't used in the industry as it's an unnecessary complication. That said, Hanamismith gets around this by building demo projects for you using the `main` branches. So you already _are_ using the pre-released versions. :wink:

When you run the following:

``` 
hanamismith build --name demo
$EDITOR demo/Gemfile
```

...you see the following:

``` 
# (truncated for brevity)
gem "hanami", github: "hanami/hanami", branch: "main"
gem "hanami-cli", github: "hanami/cli", branch: "main"
gem "hanami-controller", github: "hanami/controller", branch: "main"
gem "hanami-router", github: "hanami/router", branch: "main"
gem "hanami-utils", github: "hanami/utils", branch: "main"
gem "hanami-validations", github: "hanami/validations", branch: "main"
gem "hanami-view", github: "hanami/view", branch: "main"
```

So, yeah, you're on the pre-release!

I'm going to close this issue but feel free to continue the discussion if you like because support is already provided for you. Once Hanami reaches 2.1, Hanamismith will be updated to support 2.1 versions and move away from using the `main` branches altogether.
